# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

   

    - name: Notify Robin
      if: always() # Always run this step even if the build fails
      run: |
        curl -X POST "${{ secrets.ROBIN_WEBHOOK_URL }}/webhook" \
        -H "Content-Type: application/json"  \
        -d '{
          "status": "${{ job.status }}",
          "repo": "${{ github.repository }}",
          "branch": "${{ github.ref_name }}",
          "run_id": "${{ github.run_id }}",
          "started_at": "${{ github.event.workflow_run.created_at }}"
        }'
